### ISSUE TITLE
毎回初回に落ちるテスト直す

### ISSUE THREAD

**Issue by aiandrox** [runteq/fledge-hub#201]
そうなんよな、一つだけ毎回初回は落ちるテストがある……なぞ……

_オリジナルは @aiandrox が https://github.com/runteq/fledge-hub/pull/200#issuecomment-877588491 にポスト_

**Comment by aiandrox** [comment]
```
  1) Settings::SocialAccountsController GET /index render a successful response
     Failure/Error: all.sort_by(&:position)
     
     ArgumentError:
       comparison of Integer with nil failed
     # ./app/models/active_hash_master.rb:13:in `sort_by'
     # ./app/models/active_hash_master.rb:13:in `asc'
```

https://app.circleci.com/pipelines/github/runteq/fledge-hub/393/workflows/a682120b-ef1c-4e91-b902-b25c78f74ca5/jobs/804
