### ISSUE TITLE
本番環境でのみフォームからPOSTできない

### ISSUE THREAD

**Issue by aiandrox** [runteq/fledge-hub#232]
## 概要

フォームのPOSTができない
![image](https://user-images.githubusercontent.com/44717752/130363309-33dfb154-018d-4ddc-b5f4-da0cb000d169.png)

## 対処法など

Turboを使わなければ動くのはほぼ間違いない

https://blog.willnet.in/entry/20080509/1210338845
https://discuss.hotwired.dev/t/csrf-token-invalidauthenticitytoken/91
https://discuss.hotwired.dev/t/should-we-still-use-ujs/2569

ぶん投げてみた
https://twitter.com/aiandrox/status/1429483448016592896

**Comment by aiandrox** [comment]
@ShotaroHirose59 
エラーログ貼っといてください！

**Comment by ShotaroHirose59** [comment]
@aiandrox 
こちらです！ご確認お願いします！
```
I, [2021-08-22T16:13:58.830736 #12488]  INFO -- : [e511488a-03bd-4357-8835-fbc79a7edb61] Started GET "/registration/new" for 126.73.109.97 at 2021-08-22 16:13:58 +0000
I, [2021-08-22T16:13:58.831455 #12488]  INFO -- : [e511488a-03bd-4357-8835-fbc79a7edb61] Processing by RegistrationsController#new as HTML
I, [2021-08-22T16:13:58.847351 #12488]  INFO -- : [e511488a-03bd-4357-8835-fbc79a7edb61]   Rendered registrations/new.html.slim within layouts/application (Duration: 7.2ms | Allocations: 7197)
I, [2021-08-22T16:13:58.848624 #12488]  INFO -- : [e511488a-03bd-4357-8835-fbc79a7edb61]   Rendered layout layouts/application.html.slim (Duration: 8.6ms | Allocations: 8052)
I, [2021-08-22T16:13:58.848878 #12488]  INFO -- : [e511488a-03bd-4357-8835-fbc79a7edb61] Completed 200 OK in 17ms (Views: 9.9ms | ActiveRecord: 0.6ms | Allocations: 13297)
I, [2021-08-22T16:14:11.615088 #12488]  INFO -- : [3cdfd24c-70e5-4571-bbde-1fedfb85fc42] Started POST "/registration" for 126.73.109.97 at 2021-08-22 16:14:11 +0000
I, [2021-08-22T16:14:11.615914 #12488]  INFO -- : [3cdfd24c-70e5-4571-bbde-1fedfb85fc42] Processing by RegistrationsController#create as TURBO_STREAM
I, [2021-08-22T16:14:11.615977 #12488]  INFO -- : [3cdfd24c-70e5-4571-bbde-1fedfb85fc42]   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"screen_name"=>"ShotaroHirose59", "display_name"=>"SH59", "email"=>"shotaro199959@icloud.com"}, "acceptable"=>"true", "commit"=>"ユーザー登録"}
W, [2021-08-22T16:14:11.616131 #12488]  WARN -- : [3cdfd24c-70e5-4571-bbde-1fedfb85fc42] HTTP Origin header (https://fledge-hub.com) didn't match request.base_url (http://fledge-hub.com)
I, [2021-08-22T16:14:11.616545 #12488]  INFO -- : [3cdfd24c-70e5-4571-bbde-1fedfb85fc42] Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms | Allocations: 400)
F, [2021-08-22T16:14:11.617160 #12488] FATAL -- : [3cdfd24c-70e5-4571-bbde-1fedfb85fc42]   
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42]   
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] sorcery (0.16.1) lib/sorcery/controller.rb:125:in `handle_unverified_request'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:427:in `block in make_lambda'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:199:in `block in halting'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:512:in `block in invoke_before'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:512:in `each'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:512:in `invoke_before'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:137:in `run_callbacks'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/notifications.rb:203:in `block in instrument'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/notifications.rb:203:in `instrument'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activerecord (6.1.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/abstract_controller/base.rb:165:in `process'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionview (6.1.4) lib/action_view/rendering.rb:39:in `process'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal.rb:190:in `dispatch'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_controller/metal.rb:254:in `dispatch'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/journey/router.rb:32:in `each'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/journey/router.rb:32:in `serve'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/routing/route_set.rb:842:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/head.rb:12:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] railties (6.1.4) lib/rails/rack/logger.rb:37:in `call_app'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] railties (6.1.4) lib/rails/rack/logger.rb:26:in `block in call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/tagged_logging.rb:37:in `tagged'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/tagged_logging.rb:99:in `tagged'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] railties (6.1.4) lib/rails/rack/logger.rb:26:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] activesupport (6.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] actionpack (6.1.4) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] railties (6.1.4) lib/rails/engine.rb:539:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] puma (5.3.2) lib/puma/configuration.rb:249:in `call'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] puma (5.3.2) lib/puma/request.rb:77:in `block in handle_request'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] puma (5.3.2) lib/puma/thread_pool.rb:338:in `with_force_shutdown'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] puma (5.3.2) lib/puma/request.rb:76:in `handle_request'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] puma (5.3.2) lib/puma/server.rb:438:in `process_client'
[3cdfd24c-70e5-4571-bbde-1fedfb85fc42] puma (5.3.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```
